services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: calories_calc
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
